#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PrestamoLibrosGABRYAN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPrestamo_Libro(Prestamo_Libro instance);
    partial void UpdatePrestamo_Libro(Prestamo_Libro instance);
    partial void DeletePrestamo_Libro(Prestamo_Libro instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertEditorial(Editorial instance);
    partial void UpdateEditorial(Editorial instance);
    partial void DeleteEditorial(Editorial instance);
    partial void InsertEstudiante(Estudiante instance);
    partial void UpdateEstudiante(Estudiante instance);
    partial void DeleteEstudiante(Estudiante instance);
    partial void InsertLibro(Libro instance);
    partial void UpdateLibro(Libro instance);
    partial void DeleteLibro(Libro instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Datos.Properties.Settings.Default.PrestamoLibrosGABRYANConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Prestamo_Libro> Prestamo_Libros
		{
			get
			{
				return this.GetTable<Prestamo_Libro>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Editorial> Editorials
		{
			get
			{
				return this.GetTable<Editorial>();
			}
		}
		
		public System.Data.Linq.Table<Estudiante> Estudiantes
		{
			get
			{
				return this.GetTable<Estudiante>();
			}
		}
		
		public System.Data.Linq.Table<Libro> Libros
		{
			get
			{
				return this.GetTable<Libro>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_Devolucion")]
		public int CP_Devolucion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Prestamo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_devolucion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Prestamo, fecha_devolucion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarLibro")]
		public int CP_ModificarLibro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string autor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCat", DbType="Int")] System.Nullable<int> idCat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEdit", DbType="Int")] System.Nullable<int> idEdit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, autor, idCat, idEdit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarEstudiante")]
		public int CP_EliminarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_EliminarLibro")]
		public int CP_EliminarLibro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarCategoria")]
		public int CP_InsertarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_categoria, nombre, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarEditorial")]
		public int CP_InsertarEditorial([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Editorial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Editorial, nombre, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarEstudiante")]
		public int CP_InsertarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nacimiento", DbType="Date")] System.Nullable<System.DateTime> fecha_Nacimiento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombre, apellido, sexo, fecha_Nacimiento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarLibro")]
		public int CP_InsertarLibro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string autor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCat", DbType="Int")] System.Nullable<int> idCat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEdit", DbType="Int")] System.Nullable<int> idEdit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, autor, idCat, idEdit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_InsertarPrestamo")]
		public int CP_InsertarPrestamo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Prestamo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo_libro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_prestamo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_entrega)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Prestamo, cedula, codigo_libro, fecha_prestamo, fecha_entrega);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarCategoria")]
		public ISingleResult<CP_ListarCategoriaResult> CP_ListarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_ListarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarEditorial")]
		public ISingleResult<CP_ListarEditorialResult> CP_ListarEditorial([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_ListarEditorialResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarEstudiante")]
		public ISingleResult<CP_ListarEstudianteResult> CP_ListarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_ListarEstudianteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarLibro")]
		public ISingleResult<CP_ListarLibroResult> CP_ListarLibro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_ListarLibroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ModificarEstudiante")]
		public int CP_ModificarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nacimiento", DbType="Date")] System.Nullable<System.DateTime> fecha_Nacimiento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombre, apellido, sexo, fecha_Nacimiento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CP_ListarPrestamo")]
		public ISingleResult<CP_ListarPrestamoResult> CP_ListarPrestamo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<CP_ListarPrestamoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prestamo_Libros")]
	public partial class Prestamo_Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Prestamo;
		
		private string _Cedula_Estudiante;
		
		private int _Codigo_Libro_Retirado;
		
		private System.DateTime _Fecha_Prestamo;
		
		private System.DateTime _Fecha_Entrega;
		
		private System.Nullable<System.DateTime> _Fecha_Devolucion;
		
		private EntityRef<Estudiante> _Estudiante;
		
		private EntityRef<Libro> _Libro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PrestamoChanging(int value);
    partial void OnId_PrestamoChanged();
    partial void OnCedula_EstudianteChanging(string value);
    partial void OnCedula_EstudianteChanged();
    partial void OnCodigo_Libro_RetiradoChanging(int value);
    partial void OnCodigo_Libro_RetiradoChanged();
    partial void OnFecha_PrestamoChanging(System.DateTime value);
    partial void OnFecha_PrestamoChanged();
    partial void OnFecha_EntregaChanging(System.DateTime value);
    partial void OnFecha_EntregaChanged();
    partial void OnFecha_DevolucionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_DevolucionChanged();
    #endregion
		
		public Prestamo_Libro()
		{
			this._Estudiante = default(EntityRef<Estudiante>);
			this._Libro = default(EntityRef<Libro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Prestamo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Prestamo
		{
			get
			{
				return this._Id_Prestamo;
			}
			set
			{
				if ((this._Id_Prestamo != value))
				{
					this.OnId_PrestamoChanging(value);
					this.SendPropertyChanging();
					this._Id_Prestamo = value;
					this.SendPropertyChanged("Id_Prestamo");
					this.OnId_PrestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula_Estudiante", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula_Estudiante
		{
			get
			{
				return this._Cedula_Estudiante;
			}
			set
			{
				if ((this._Cedula_Estudiante != value))
				{
					if (this._Estudiante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCedula_EstudianteChanging(value);
					this.SendPropertyChanging();
					this._Cedula_Estudiante = value;
					this.SendPropertyChanged("Cedula_Estudiante");
					this.OnCedula_EstudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Libro_Retirado", DbType="Int NOT NULL")]
		public int Codigo_Libro_Retirado
		{
			get
			{
				return this._Codigo_Libro_Retirado;
			}
			set
			{
				if ((this._Codigo_Libro_Retirado != value))
				{
					if (this._Libro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigo_Libro_RetiradoChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Libro_Retirado = value;
					this.SendPropertyChanged("Codigo_Libro_Retirado");
					this.OnCodigo_Libro_RetiradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Prestamo", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Prestamo
		{
			get
			{
				return this._Fecha_Prestamo;
			}
			set
			{
				if ((this._Fecha_Prestamo != value))
				{
					this.OnFecha_PrestamoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Prestamo = value;
					this.SendPropertyChanged("Fecha_Prestamo");
					this.OnFecha_PrestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Entrega", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Entrega
		{
			get
			{
				return this._Fecha_Entrega;
			}
			set
			{
				if ((this._Fecha_Entrega != value))
				{
					this.OnFecha_EntregaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Entrega = value;
					this.SendPropertyChanged("Fecha_Entrega");
					this.OnFecha_EntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Devolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Devolucion
		{
			get
			{
				return this._Fecha_Devolucion;
			}
			set
			{
				if ((this._Fecha_Devolucion != value))
				{
					this.OnFecha_DevolucionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Devolucion = value;
					this.SendPropertyChanged("Fecha_Devolucion");
					this.OnFecha_DevolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estudiante_Prestamo_Libro", Storage="_Estudiante", ThisKey="Cedula_Estudiante", OtherKey="Cedula", IsForeignKey=true)]
		public Estudiante Estudiante
		{
			get
			{
				return this._Estudiante.Entity;
			}
			set
			{
				Estudiante previousValue = this._Estudiante.Entity;
				if (((previousValue != value) 
							|| (this._Estudiante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estudiante.Entity = null;
						previousValue.Prestamo_Libros.Remove(this);
					}
					this._Estudiante.Entity = value;
					if ((value != null))
					{
						value.Prestamo_Libros.Add(this);
						this._Cedula_Estudiante = value.Cedula;
					}
					else
					{
						this._Cedula_Estudiante = default(string);
					}
					this.SendPropertyChanged("Estudiante");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libro_Prestamo_Libro", Storage="_Libro", ThisKey="Codigo_Libro_Retirado", OtherKey="Codigo", IsForeignKey=true)]
		public Libro Libro
		{
			get
			{
				return this._Libro.Entity;
			}
			set
			{
				Libro previousValue = this._Libro.Entity;
				if (((previousValue != value) 
							|| (this._Libro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Libro.Entity = null;
						previousValue.Prestamo_Libros.Remove(this);
					}
					this._Libro.Entity = value;
					if ((value != null))
					{
						value.Prestamo_Libros.Add(this);
						this._Codigo_Libro_Retirado = value.Codigo;
					}
					else
					{
						this._Codigo_Libro_Retirado = default(int);
					}
					this.SendPropertyChanged("Libro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Categoria;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private EntitySet<Libro> _Libros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CategoriaChanging(int value);
    partial void OnId_CategoriaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Categoria()
		{
			this._Libros = new EntitySet<Libro>(new Action<Libro>(this.attach_Libros), new Action<Libro>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Categoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Categoria
		{
			get
			{
				return this._Id_Categoria;
			}
			set
			{
				if ((this._Id_Categoria != value))
				{
					this.OnId_CategoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_Categoria = value;
					this.SendPropertyChanged("Id_Categoria");
					this.OnId_CategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Libro", Storage="_Libros", ThisKey="Id_Categoria", OtherKey="Id_Categoria")]
		public EntitySet<Libro> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Libros(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Editorial")]
	public partial class Editorial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Editorial;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private EntitySet<Libro> _Libros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_EditorialChanging(int value);
    partial void OnId_EditorialChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Editorial()
		{
			this._Libros = new EntitySet<Libro>(new Action<Libro>(this.attach_Libros), new Action<Libro>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Editorial", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Editorial
		{
			get
			{
				return this._Id_Editorial;
			}
			set
			{
				if ((this._Id_Editorial != value))
				{
					this.OnId_EditorialChanging(value);
					this.SendPropertyChanging();
					this._Id_Editorial = value;
					this.SendPropertyChanged("Id_Editorial");
					this.OnId_EditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Editorial_Libro", Storage="_Libros", ThisKey="Id_Editorial", OtherKey="Id_Editorial")]
		public EntitySet<Libro> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Editorial = this;
		}
		
		private void detach_Libros(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Editorial = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estudiante")]
	public partial class Estudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private char _Sexo;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Estado;
		
		private EntitySet<Prestamo_Libro> _Prestamo_Libros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnSexoChanging(char value);
    partial void OnSexoChanged();
    partial void OnFecha_NacimientoChanging(System.DateTime value);
    partial void OnFecha_NacimientoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public Estudiante()
		{
			this._Prestamo_Libros = new EntitySet<Prestamo_Libro>(new Action<Prestamo_Libro>(this.attach_Prestamo_Libros), new Action<Prestamo_Libro>(this.detach_Prestamo_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1) NOT NULL")]
		public char Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nacimiento", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this.OnFecha_NacimientoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Nacimiento = value;
					this.SendPropertyChanged("Fecha_Nacimiento");
					this.OnFecha_NacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estudiante_Prestamo_Libro", Storage="_Prestamo_Libros", ThisKey="Cedula", OtherKey="Cedula_Estudiante")]
		public EntitySet<Prestamo_Libro> Prestamo_Libros
		{
			get
			{
				return this._Prestamo_Libros;
			}
			set
			{
				this._Prestamo_Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prestamo_Libros(Prestamo_Libro entity)
		{
			this.SendPropertyChanging();
			entity.Estudiante = this;
		}
		
		private void detach_Prestamo_Libros(Prestamo_Libro entity)
		{
			this.SendPropertyChanging();
			entity.Estudiante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Libro")]
	public partial class Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Nombre;
		
		private string _Autor;
		
		private int _Id_Categoria;
		
		private int _Id_Editorial;
		
		private string _Estado;
		
		private EntitySet<Prestamo_Libro> _Prestamo_Libros;
		
		private EntityRef<Categoria> _Categoria;
		
		private EntityRef<Editorial> _Editorial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnId_CategoriaChanging(int value);
    partial void OnId_CategoriaChanged();
    partial void OnId_EditorialChanging(int value);
    partial void OnId_EditorialChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public Libro()
		{
			this._Prestamo_Libros = new EntitySet<Prestamo_Libro>(new Action<Prestamo_Libro>(this.attach_Prestamo_Libros), new Action<Prestamo_Libro>(this.detach_Prestamo_Libros));
			this._Categoria = default(EntityRef<Categoria>);
			this._Editorial = default(EntityRef<Editorial>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this.OnAutorChanging(value);
					this.SendPropertyChanging();
					this._Autor = value;
					this.SendPropertyChanged("Autor");
					this.OnAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Categoria", DbType="Int NOT NULL")]
		public int Id_Categoria
		{
			get
			{
				return this._Id_Categoria;
			}
			set
			{
				if ((this._Id_Categoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_CategoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_Categoria = value;
					this.SendPropertyChanged("Id_Categoria");
					this.OnId_CategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Editorial", DbType="Int NOT NULL")]
		public int Id_Editorial
		{
			get
			{
				return this._Id_Editorial;
			}
			set
			{
				if ((this._Id_Editorial != value))
				{
					if (this._Editorial.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_EditorialChanging(value);
					this.SendPropertyChanging();
					this._Id_Editorial = value;
					this.SendPropertyChanged("Id_Editorial");
					this.OnId_EditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libro_Prestamo_Libro", Storage="_Prestamo_Libros", ThisKey="Codigo", OtherKey="Codigo_Libro_Retirado")]
		public EntitySet<Prestamo_Libro> Prestamo_Libros
		{
			get
			{
				return this._Prestamo_Libros;
			}
			set
			{
				this._Prestamo_Libros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Libro", Storage="_Categoria", ThisKey="Id_Categoria", OtherKey="Id_Categoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._Id_Categoria = value.Id_Categoria;
					}
					else
					{
						this._Id_Categoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Editorial_Libro", Storage="_Editorial", ThisKey="Id_Editorial", OtherKey="Id_Editorial", IsForeignKey=true)]
		public Editorial Editorial
		{
			get
			{
				return this._Editorial.Entity;
			}
			set
			{
				Editorial previousValue = this._Editorial.Entity;
				if (((previousValue != value) 
							|| (this._Editorial.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Editorial.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Editorial.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._Id_Editorial = value.Id_Editorial;
					}
					else
					{
						this._Id_Editorial = default(int);
					}
					this.SendPropertyChanged("Editorial");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prestamo_Libros(Prestamo_Libro entity)
		{
			this.SendPropertyChanging();
			entity.Libro = this;
		}
		
		private void detach_Prestamo_Libros(Prestamo_Libro entity)
		{
			this.SendPropertyChanging();
			entity.Libro = null;
		}
	}
	
	public partial class CP_ListarCategoriaResult
	{
		
		private int _Id_Categoria;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		public CP_ListarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Categoria", DbType="Int NOT NULL")]
		public int Id_Categoria
		{
			get
			{
				return this._Id_Categoria;
			}
			set
			{
				if ((this._Id_Categoria != value))
				{
					this._Id_Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class CP_ListarEditorialResult
	{
		
		private int _Id_Editorial;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		public CP_ListarEditorialResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Editorial", DbType="Int NOT NULL")]
		public int Id_Editorial
		{
			get
			{
				return this._Id_Editorial;
			}
			set
			{
				if ((this._Id_Editorial != value))
				{
					this._Id_Editorial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class CP_ListarEstudianteResult
	{
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private char _Sexo;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Estado;
		
		public CP_ListarEstudianteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1) NOT NULL")]
		public char Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nacimiento", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class CP_ListarLibroResult
	{
		
		private int _Codigo;
		
		private string _Nombre;
		
		private string _Autor;
		
		private int _Id_Categoria;
		
		private int _Id_Editorial;
		
		private string _Estado;
		
		public CP_ListarLibroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this._Autor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Categoria", DbType="Int NOT NULL")]
		public int Id_Categoria
		{
			get
			{
				return this._Id_Categoria;
			}
			set
			{
				if ((this._Id_Categoria != value))
				{
					this._Id_Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Editorial", DbType="Int NOT NULL")]
		public int Id_Editorial
		{
			get
			{
				return this._Id_Editorial;
			}
			set
			{
				if ((this._Id_Editorial != value))
				{
					this._Id_Editorial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class CP_ListarPrestamoResult
	{
		
		private int _Id_Prestamo;
		
		private string _Cedula_Estudiante;
		
		private int _Codigo_Libro_Retirado;
		
		private System.DateTime _Fecha_Prestamo;
		
		private System.DateTime _Fecha_Entrega;
		
		private System.Nullable<System.DateTime> _Fecha_Devolucion;
		
		public CP_ListarPrestamoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Prestamo", DbType="Int NOT NULL")]
		public int Id_Prestamo
		{
			get
			{
				return this._Id_Prestamo;
			}
			set
			{
				if ((this._Id_Prestamo != value))
				{
					this._Id_Prestamo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula_Estudiante", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula_Estudiante
		{
			get
			{
				return this._Cedula_Estudiante;
			}
			set
			{
				if ((this._Cedula_Estudiante != value))
				{
					this._Cedula_Estudiante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Libro_Retirado", DbType="Int NOT NULL")]
		public int Codigo_Libro_Retirado
		{
			get
			{
				return this._Codigo_Libro_Retirado;
			}
			set
			{
				if ((this._Codigo_Libro_Retirado != value))
				{
					this._Codigo_Libro_Retirado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Prestamo", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Prestamo
		{
			get
			{
				return this._Fecha_Prestamo;
			}
			set
			{
				if ((this._Fecha_Prestamo != value))
				{
					this._Fecha_Prestamo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Entrega", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Entrega
		{
			get
			{
				return this._Fecha_Entrega;
			}
			set
			{
				if ((this._Fecha_Entrega != value))
				{
					this._Fecha_Entrega = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Devolucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Devolucion
		{
			get
			{
				return this._Fecha_Devolucion;
			}
			set
			{
				if ((this._Fecha_Devolucion != value))
				{
					this._Fecha_Devolucion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
